### ISSUE TITLE
Pipeline Icon not showing

### ISSUE THREAD

**Issue by Ginzou-3** [Avaiga/taipy-studio#142]
Hello, i tried to build a simple worklfow with taipy Studio in VS. I followed yout tutorials on youtube, but the option to add a pipeline in the taipy view is missing. Did i forget something? Using Windows 10, Taipy Studio v2.0.0, Taipy Version 3.0. Tried it also on a different machine.

![grafik](https://github.com/Avaiga/taipy-studio/assets/57178420/fcf25c9d-7e9e-43ac-8837-5dfc6b1c3bad)

![grafik](https://github.com/Avaiga/taipy-studio/assets/57178420/a06e60f0-f12e-41f7-976c-a0673ad1717b)

Here is the config file: `
[CORE]
core_version="3.0"

[SCENARIO.SCENARIO_1]
tasks = [ "TASK_1:SECTION" ]

[TASK.merge]
inputs = [ "datapath_1:SECTION", "datapath_2:SECTION" ]
outputs = [ "merged_data:SECTION" ]
function = "functions.merge_dataframe.merge:function"
skippable = "False:bool"

[TASK.aggregate]
inputs = [ "merged_data:SECTION" ]
outputs = [ "aggragated_data:SECTION" ]
function = "functions.data_aggregate.main:function"
skippable = "False:bool"

[TASK.filter]
inputs = [ "aggragated_data:SECTION" ]
outputs = [ "filtered_data:SECTION" ]
function = "functions.filter_columns.out:function"
skippable = "False:bool"

[TASK.plot]
inputs = [ "filtered_data:SECTION" ]
outputs = [ "output:SECTION" ]
function = "functions.plot_graph.main:function"
skippable = "False:bool"

[DATA_NODE.datapath_1]
storage_type = "json"
default_path = "data/sim_data.json"
scope = "SCENARIO:SCOPE"

[DATA_NODE.datapath_2]
storage_type = "json"
default_path = "data/sim_params_json"
scope = "SCENARIO:SCOPE"

[DATA_NODE.merged_data]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"

[DATA_NODE.aggragated_data]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"

[DATA_NODE.filtered_data]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"

[DATA_NODE.output]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"
`

**Comment by FredLL-Avaiga** [comment]
Pipeline Entity has been removed from Taipy 3.0
It is replaced by the concept of Sequence
You can add Sequences from the Scenario view (left on your screenshot) by selecting a Scenario and then clicking on the + icon

**Comment by FredLL-Avaiga** [comment]
@Ginzou-3
Does this answer you question ?
If so, can we mark that issue as done ?
