### ISSUE TITLE
BUG-Awkward way to delete an edge

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy-studio#143]
**Description**
Linked to Avaiga/taipy#385 
Now that pressing "del" when selecting a node deletes it instead of deleting edges, there is no way to delete edges. In my opinion, the way to delete edges should be clicking on an edge selects it and pressing "del" deletes it

**Runtime environment**
Please specify relevant indications.
 - OS: Windows 11
 - Taipy Studio Config version: 2.0

**Comment by jrobinAV** [comment]
![image](https://github.com/Avaiga/taipy-studio/assets/88036007/61fb84a5-7c02-4d35-8cb2-05426d1cbd7e)

**Comment by FredLL-Avaiga** [comment]
The underlying library doesn't allow such a big change in UI event management
